"""fixed follows table

Revision ID: bc9439701e57
Revises: 0bf5b327f57f
Create Date: 2021-12-06 13:26:53.634115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc9439701e57'
down_revision = '0bf5b327f57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.add_column('follows', sa.Column('follower_id', sa.Integer(), nullable=True))
    op.add_column('follows', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.drop_constraint('follows_user_id_fkey', 'follows', type_='foreignkey')
    op.drop_constraint('follows_other_id_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.drop_column('follows', 'user_id')
    op.drop_column('follows', 'other_id')
    op.drop_column('follows', 'updatedAt')
    op.drop_column('follows', 'id')
    op.drop_column('follows', 'createdAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('follows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('follows', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('follows', sa.Column('other_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('follows', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_other_id_fkey', 'follows', 'users', ['other_id'], ['id'])
    op.create_foreign_key('follows_user_id_fkey', 'follows', 'users', ['user_id'], ['id'])
    op.drop_column('follows', 'followed_id')
    op.drop_column('follows', 'follower_id')
    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('other_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['other_id'], ['users.id'], name='followers_other_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='followers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='followers_pkey')
    )
    # ### end Alembic commands ###
