"""empty message

Revision ID: e202db764d39
Revises: 77413102b34e
Create Date: 2021-12-13 09:04:00.539944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e202db764d39'
down_revision = '77413102b34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'like')
    # ### end Alembic commands ###
