"""attempting migration

Revision ID: 08b95a91f54e
Revises: e8011a0aafd4
Create Date: 2021-12-06 12:36:02.205779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08b95a91f54e'
down_revision = 'e8011a0aafd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdA', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdA')
    # ### end Alembic commands ###
