"""empty message

Revision ID: 77413102b34e
Revises: 5a2095907636
Create Date: 2021-12-12 20:10:16.403077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77413102b34e'
down_revision = '5a2095907636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
