"""fixed follows table

Revision ID: 6767545724e9
Revises: bc9439701e57
Create Date: 2021-12-06 13:51:08.119615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6767545724e9'
down_revision = 'bc9439701e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.drop_column('users', 'createdA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdA', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'createdAt')
    # ### end Alembic commands ###
